#* ************************************************************************** *#
#*                                                                            *#
#*                                                        :::      ::::::::   *#
#*   target_rule.mk                                     :+:      :+:    :+:   *#
#*                                                    +:+ +:+         +:+     *#
#*   By: mgautier <mgautier@student.42.fr>          +#+  +:+       +#+        *#
#*                                                +#+#+#+#+#+   +#+           *#
#*   Created: 2017/10/19 19:15:27 by mgautier          #+#    #+#             *#
#*   Updated: 2017/10/24 19:53:37 by                  ###   ########.fr       *#
#*                                                                            *#
#* ************************************************************************** *#

#
# This file deals with the target generated by one directory.
#

intermediate_target =\
 $(intermediate_target_prefix)$(TARGET$1)$(intermediate_target_suffix)
# define a make rule for the target of the directory given as parameters
# 1 : directory_name

define define_target_rule

$(if $(TARGET$1),,$(warning No target for $1))

$(intermediate_target$1):$(full_path_OBJ$1)
	$(QUIET) $$(static_lib)

$(target$1): $(intermediate_target$1) $(DEPS$1)
	$(QUIET) $$(link_exec)
endef
